# Site settings
title: David Mazza
email: davidedwardmazza@gmail.com
description: "I am a designer. I design and implement UI/UX for software and this."
baseurl: ""
url: "http://davidmazza.com"
twitter_username: dmzza
github_username:  dmzza

# Build settings
markdown: kramdown
permalink: pretty
