development:
  adapter: postgresql
  database: george_development
  host: localhost
  username: david
  password:

test:
  adapter: postgresql
  database: george_test
  host: localhost
  username: david
  password: